#!/bin/sh

set -e


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p lubuntu-software-center 
fi

# End automatically added section


if [ "$1" = "triggered" ] || [ "$1" = "configure" ]; then

    # update the application data
    lubuntu-software-center-build-db /var/cache/lsc_packages.db /usr/share/app-install/desktop/ /usr/share/LSC/categories.ini || true
    exit 0
fi
