#! /bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -e /etc/rc2.d/S20ubiquity ]; then
	update-rc.d -f ubiquity remove >/dev/null 2>&1
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/ubiquity" ]; then
	update-rc.d ubiquity defaults >/dev/null
fi
# End automatically added section

# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p ubiquity /usr/lib/ubiquity -V 3.1-
fi

# End automatically added section


exit 0
